//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Customer
    {
        
        [Required(ErrorMessage = "Không để trống!")]
       // [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Email nhập sai. Mời nhập lại! Ví dụ example@gmail.com")]
        public string Username { get; set; }
        [MinLength(8, ErrorMessage = "Mật khẩu phải ít nhất 8 ký tự!")]
        [Required(ErrorMessage = "Không để trống!")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "Không để trống!")]
        public string FullName { get; set; }
        public string Address { get; set; }
        [Required(ErrorMessage = "Không để trống!")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Email nhập sai. Mời nhập lại! Ví dụ example@gmail.com")]
        [DataType(DataType.Password,ErrorMessage ="Địa chỉ Email phải trùng với Username")]
        public string Email { get; set; }
        public string Photo { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
    }
}
